# Generated by Django 5.1.1 on 2024-10-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="Amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="Bidder",
            new_name="bidder",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="Listing",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="Commenter",
            new_name="commenter",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="Listing",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="Text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="Active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="Owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="Title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="Starting_Bid",
        ),
    ]
