# Generated by Django 5.1.1 on 2024-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_amount_bid_amount_rename_bidder_bid_bidder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchers", to="auctions.listing"
            ),
        ),
    ]
